#kubectl run n1 --image=nginx --port=80
#kubectl expose pod n1 --port=80 --target-port=80 --name=n1svc --type=NodePort
apiVersion: v1
kind: Pod
metadata:
  name: n1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: "jenkins/jenkins:lts"
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: n1
  labels:
    app: nginx
    env: dev
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: n1
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "jenkins/jenkins:lts"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: ReplicaSet
metadata:
  name: n1
  labels:
    app: nginx
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      env: dev
  template:
    metadata:
      name: n1
      labels:
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx
        image: "nginx:3.2.1"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deploy
metadata:
  name: n1
  labels:
    app: nginx
    env: dev
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      env: dev
  template:
    metadata:
      name: n1
      labels:
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx
        image: "jenkins/jenkins:lts"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: n1svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31815
